export const DiseaseData = [
  {
    subjectComponents: null,
    annotationName: null,
    annotationHash: null,
    isoformsDisplayedAsSpecific: [],
    synonyms: null,
    uniqueName: "AN_P37840_000417",
    cvTermAccessionCode: null,
    cvTermName: null,
    cvTermType: null,
    cvTermDescription: null,
    cvApiName: null,
    description:
      "Genetic alterations of SNCA resulting in aberrant polymerization into fibrils, are associated with several neurodegenerative diseases (synucleinopathies). SNCA fibrillar aggregates represent the major non A-beta component of Alzheimer disease amyloid plaque, and a major component of Lewy body inclusions. They are also found within Lewy body (LB)-like intraneuronal inclusions, glial inclusions and axonal spheroids in neurodegeneration with brain iron accumulation type 1.",
    category: "disease",
    qualityQualifier: "GOLD",
    annotationId: 34855083,
    variant: null,
    synonym: null,
    evidences: [
      {
        resourceId: 1352405,
        resourceType: "database",
        resourceAccession: "P37840",
        resourceDb: "UniProt",
        experimentalContextId: 0,
        mdataId: null,
        annotationId: 34855083,
        qualifierType: null,
        qualityQualifier: "GOLD",
        evidenceId: 84734617,
        assignedBy: "Uniprot",
        goAssignedBy: null,
        assignmentMethod: "curated",
        evidenceCodeAC: "ECO:0000269",
        evidenceCodeName: "experimental evidence used in manual assertion",
        evidenceCodeOntology: "EvidenceCodeOntologyCv",
        note: null,
        resourceAssociationType: "evidence",
        valid: true,
        properties: {},
        resourceDescription: "UniProt web site",
        resourceAPublication: false,
        negativeIsoformSpecificity: null,
        cl: null,
        isoformSpecificity: null,
        referenceIdentifierAccession: null,
        sampleId: null,
        sp: null,
        expressionLevel: null,
        integrationLevel: null,
        antibodies: null,
        intensity: null,
        subjectProteinOrigin: null,
        sourceAccession_TODEBUG: null,
        negativeEvidence: false,
        propertiesNames: [],
        goQualifier: null,
        resourceAXref: true
      }
    ],
    indirectEvidenceRefList: null,
    targetingIsoformsMap: {
      "NX_P37840-1": {
        annotationId: 34855083,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-1",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-1",
        positional: false
      },
      "NX_P37840-2": {
        annotationId: 34855083,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-2",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-2",
        positional: false
      },
      "NX_P37840-3": {
        annotationId: 34855083,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-3",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-3",
        positional: false
      }
    },
    properties: [
      {
        annotationId: 34855083,
        valueType: null,
        name: "rank",
        value: "1",
        accession: null
      }
    ],
    bioObject: null,
    parentXref: null,
    proteoformAnnotation: false,
    wildTypeAnnotation: true,
    apicategory: "DISEASE",
    apiTypeName: "Disease",
    propertiesMap: {
      rank: [
        {
          annotationId: 34855083,
          valueType: null,
          name: "rank",
          value: "1",
          accession: null
        }
      ]
    },
    categoryName: "Disease",
    rdfPredicate: "disease",
    parentPredicates: ["generalAnnotation", "medical"]
  },
  {
    subjectComponents: null,
    annotationName: null,
    annotationHash: null,
    isoformsDisplayedAsSpecific: [],
    synonyms: null,
    uniqueName: "AN_P37840_000424",
    cvTermAccessionCode: "DI-01901",
    cvTermName: "Dementia Lewy body",
    cvTermType: null,
    cvTermDescription:
      "A neurodegenerative disorder characterized by mental impairment leading to dementia, parkinsonism, fluctuating cognitive function, visual hallucinations, falls, syncopal episodes, and sensitivity to neuroleptic medication. Brainstem or cortical intraneuronal accumulations of aggregated proteins (Lewy bodies) are the only essential pathologic features. Patients may also have hippocampal and neocortical senile plaques, sometimes in sufficient number to fulfill the diagnostic criteria for Alzheimer disease.",
    cvApiName: "UniprotDiseaseCv",
    description:
      "Dementia Lewy body (DLB) [MIM:127750]: A neurodegenerative disorder characterized by mental impairment leading to dementia, parkinsonism, fluctuating cognitive function, visual hallucinations, falls, syncopal episodes, and sensitivity to neuroleptic medication. Brainstem or cortical intraneuronal accumulations of aggregated proteins (Lewy bodies) are the only essential pathologic features. Patients may also have hippocampal and neocortical senile plaques, sometimes in sufficient number to fulfill the diagnostic criteria for Alzheimer disease. The disease is caused by mutations affecting the gene represented in this entry.",
    category: "disease",
    qualityQualifier: "GOLD",
    annotationId: 34913934,
    variant: null,
    synonym: null,
    evidences: [
      {
        resourceId: 1352405,
        resourceType: "database",
        resourceAccession: "P37840",
        resourceDb: "UniProt",
        experimentalContextId: 0,
        mdataId: null,
        annotationId: 34913934,
        qualifierType: null,
        qualityQualifier: "GOLD",
        evidenceId: 84734630,
        assignedBy: "Uniprot",
        goAssignedBy: null,
        assignmentMethod: "curated",
        evidenceCodeAC: "ECO:0000269",
        evidenceCodeName: "experimental evidence used in manual assertion",
        evidenceCodeOntology: "EvidenceCodeOntologyCv",
        note: null,
        resourceAssociationType: "evidence",
        valid: true,
        properties: {},
        resourceDescription: "UniProt web site",
        resourceAPublication: false,
        negativeIsoformSpecificity: null,
        cl: null,
        isoformSpecificity: null,
        referenceIdentifierAccession: null,
        sampleId: null,
        sp: null,
        expressionLevel: null,
        integrationLevel: null,
        antibodies: null,
        intensity: null,
        subjectProteinOrigin: null,
        sourceAccession_TODEBUG: null,
        negativeEvidence: false,
        propertiesNames: [],
        goQualifier: null,
        resourceAXref: true
      },
      {
        resourceId: 648403,
        resourceType: "publication",
        resourceAccession: null,
        resourceDb: null,
        experimentalContextId: 0,
        mdataId: null,
        annotationId: 34913934,
        qualifierType: null,
        qualityQualifier: "GOLD",
        evidenceId: 84734631,
        assignedBy: "Uniprot",
        goAssignedBy: null,
        assignmentMethod: "curated",
        evidenceCodeAC: "ECO:0000269",
        evidenceCodeName: "experimental evidence used in manual assertion",
        evidenceCodeOntology: "EvidenceCodeOntologyCv",
        note: null,
        resourceAssociationType: "evidence",
        valid: true,
        properties: {},
        resourceDescription: null,
        resourceAPublication: true,
        negativeIsoformSpecificity: null,
        cl: null,
        isoformSpecificity: null,
        referenceIdentifierAccession: null,
        sampleId: null,
        sp: null,
        expressionLevel: null,
        integrationLevel: null,
        antibodies: null,
        intensity: null,
        subjectProteinOrigin: null,
        sourceAccession_TODEBUG: null,
        negativeEvidence: false,
        propertiesNames: [],
        goQualifier: null,
        resourceAXref: false
      }
    ],
    indirectEvidenceRefList: null,
    targetingIsoformsMap: {
      "NX_P37840-1": {
        annotationId: 34913934,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-1",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-1",
        positional: false
      },
      "NX_P37840-2": {
        annotationId: 34913934,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-2",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-2",
        positional: false
      },
      "NX_P37840-3": {
        annotationId: 34913934,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-3",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-3",
        positional: false
      }
    },
    properties: [
      {
        annotationId: 34913934,
        valueType: "resource-internal-ref",
        name: "alternative disease description",
        value: "62185",
        accession: "127750"
      },
      {
        annotationId: 34913934,
        valueType: null,
        name: "rank",
        value: "4",
        accession: null
      }
    ],
    bioObject: null,
    parentXref: null,
    proteoformAnnotation: false,
    wildTypeAnnotation: true,
    apicategory: "DISEASE",
    apiTypeName: "Disease",
    propertiesMap: {
      "alternative disease description": [
        {
          annotationId: 34913934,
          valueType: "resource-internal-ref",
          name: "alternative disease description",
          value: "62185",
          accession: "127750"
        }
      ],
      rank: [
        {
          annotationId: 34913934,
          valueType: null,
          name: "rank",
          value: "4",
          accession: null
        }
      ]
    },
    categoryName: "Disease",
    rdfPredicate: "disease",
    parentPredicates: ["generalAnnotation", "medical"]
  },
  {
    subjectComponents: null,
    annotationName: null,
    annotationHash: null,
    isoformsDisplayedAsSpecific: [],
    synonyms: null,
    uniqueName: "AN_P37840_000807",
    cvTermAccessionCode: "DI-01223",
    cvTermName: "Parkinson disease 1, autosomal dominant",
    cvTermType: null,
    cvTermDescription:
      "A complex neurodegenerative disorder characterized by bradykinesia, resting tremor, muscular rigidity and postural instability. Additional features are characteristic postural abnormalities, dysautonomia, dystonic cramps, and dementia. The pathology of Parkinson disease involves the loss of dopaminergic neurons in the substantia nigra and the presence of Lewy bodies (intraneuronal accumulations of aggregated proteins), in surviving neurons in various areas of the brain. The disease is progressive and usually manifests after the age of 50 years, although early-onset cases (before 50 years) are known. The majority of the cases are sporadic suggesting a multifactorial etiology based on environmental and genetic factors. However, some patients present with a positive family history for the disease. Familial forms of the disease usually begin at earlier ages and are associated with atypical clinical features.",
    cvApiName: "UniprotDiseaseCv",
    description:
      "Parkinson disease 1, autosomal dominant (PARK1) [MIM:168601]: A complex neurodegenerative disorder characterized by bradykinesia, resting tremor, muscular rigidity and postural instability. Additional features are characteristic postural abnormalities, dysautonomia, dystonic cramps, and dementia. The pathology of Parkinson disease involves the loss of dopaminergic neurons in the substantia nigra and the presence of Lewy bodies (intraneuronal accumulations of aggregated proteins), in surviving neurons in various areas of the brain. The disease is progressive and usually manifests after the age of 50 years, although early-onset cases (before 50 years) are known. The majority of the cases are sporadic suggesting a multifactorial etiology based on environmental and genetic factors. However, some patients present with a positive family history for the disease. Familial forms of the disease usually begin at earlier ages and are associated with atypical clinical features. The disease is caused by mutations affecting the gene represented in this entry.",
    category: "disease",
    qualityQualifier: "GOLD",
    annotationId: 51978577,
    variant: null,
    synonym: null,
    evidences: [
      {
        resourceId: 736451,
        resourceType: "publication",
        resourceAccession: null,
        resourceDb: null,
        experimentalContextId: 0,
        mdataId: null,
        annotationId: 51978577,
        qualifierType: null,
        qualityQualifier: "GOLD",
        evidenceId: 119516115,
        assignedBy: "Uniprot",
        goAssignedBy: null,
        assignmentMethod: "curated",
        evidenceCodeAC: "ECO:0000269",
        evidenceCodeName: "experimental evidence used in manual assertion",
        evidenceCodeOntology: "EvidenceCodeOntologyCv",
        note: null,
        resourceAssociationType: "evidence",
        valid: true,
        properties: {},
        resourceDescription: null,
        resourceAPublication: true,
        negativeIsoformSpecificity: null,
        cl: null,
        isoformSpecificity: null,
        referenceIdentifierAccession: null,
        sampleId: null,
        sp: null,
        expressionLevel: null,
        integrationLevel: null,
        antibodies: null,
        intensity: null,
        subjectProteinOrigin: null,
        sourceAccession_TODEBUG: null,
        negativeEvidence: false,
        propertiesNames: [],
        goQualifier: null,
        resourceAXref: false
      },
      {
        resourceId: 29257148,
        resourceType: "publication",
        resourceAccession: null,
        resourceDb: null,
        experimentalContextId: 0,
        mdataId: null,
        annotationId: 51978577,
        qualifierType: null,
        qualityQualifier: "GOLD",
        evidenceId: 119516117,
        assignedBy: "Uniprot",
        goAssignedBy: null,
        assignmentMethod: "curated",
        evidenceCodeAC: "ECO:0000269",
        evidenceCodeName: "experimental evidence used in manual assertion",
        evidenceCodeOntology: "EvidenceCodeOntologyCv",
        note: null,
        resourceAssociationType: "evidence",
        valid: true,
        properties: {},
        resourceDescription: null,
        resourceAPublication: true,
        negativeIsoformSpecificity: null,
        cl: null,
        isoformSpecificity: null,
        referenceIdentifierAccession: null,
        sampleId: null,
        sp: null,
        expressionLevel: null,
        integrationLevel: null,
        antibodies: null,
        intensity: null,
        subjectProteinOrigin: null,
        sourceAccession_TODEBUG: null,
        negativeEvidence: false,
        propertiesNames: [],
        goQualifier: null,
        resourceAXref: false
      },
      {
        resourceId: 42610232,
        resourceType: "publication",
        resourceAccession: null,
        resourceDb: null,
        experimentalContextId: 0,
        mdataId: null,
        annotationId: 51978577,
        qualifierType: null,
        qualityQualifier: "GOLD",
        evidenceId: 119516114,
        assignedBy: "Uniprot",
        goAssignedBy: null,
        assignmentMethod: "curated",
        evidenceCodeAC: "ECO:0000269",
        evidenceCodeName: "experimental evidence used in manual assertion",
        evidenceCodeOntology: "EvidenceCodeOntologyCv",
        note: null,
        resourceAssociationType: "evidence",
        valid: true,
        properties: {},
        resourceDescription: null,
        resourceAPublication: true,
        negativeIsoformSpecificity: null,
        cl: null,
        isoformSpecificity: null,
        referenceIdentifierAccession: null,
        sampleId: null,
        sp: null,
        expressionLevel: null,
        integrationLevel: null,
        antibodies: null,
        intensity: null,
        subjectProteinOrigin: null,
        sourceAccession_TODEBUG: null,
        negativeEvidence: false,
        propertiesNames: [],
        goQualifier: null,
        resourceAXref: false
      },
      {
        resourceId: 1352405,
        resourceType: "database",
        resourceAccession: "P37840",
        resourceDb: "UniProt",
        experimentalContextId: 0,
        mdataId: null,
        annotationId: 51978577,
        qualifierType: null,
        qualityQualifier: "GOLD",
        evidenceId: 119516119,
        assignedBy: "Uniprot",
        goAssignedBy: null,
        assignmentMethod: "curated",
        evidenceCodeAC: "ECO:0000269",
        evidenceCodeName: "experimental evidence used in manual assertion",
        evidenceCodeOntology: "EvidenceCodeOntologyCv",
        note: null,
        resourceAssociationType: "evidence",
        valid: true,
        properties: {},
        resourceDescription: "UniProt web site",
        resourceAPublication: false,
        negativeIsoformSpecificity: null,
        cl: null,
        isoformSpecificity: null,
        referenceIdentifierAccession: null,
        sampleId: null,
        sp: null,
        expressionLevel: null,
        integrationLevel: null,
        antibodies: null,
        intensity: null,
        subjectProteinOrigin: null,
        sourceAccession_TODEBUG: null,
        negativeEvidence: false,
        propertiesNames: [],
        goQualifier: null,
        resourceAXref: true
      },
      {
        resourceId: 704114,
        resourceType: "publication",
        resourceAccession: null,
        resourceDb: null,
        experimentalContextId: 0,
        mdataId: null,
        annotationId: 51978577,
        qualifierType: null,
        qualityQualifier: "GOLD",
        evidenceId: 119516120,
        assignedBy: "Uniprot",
        goAssignedBy: null,
        assignmentMethod: "curated",
        evidenceCodeAC: "ECO:0000269",
        evidenceCodeName: "experimental evidence used in manual assertion",
        evidenceCodeOntology: "EvidenceCodeOntologyCv",
        note: null,
        resourceAssociationType: "evidence",
        valid: true,
        properties: {},
        resourceDescription: null,
        resourceAPublication: true,
        negativeIsoformSpecificity: null,
        cl: null,
        isoformSpecificity: null,
        referenceIdentifierAccession: null,
        sampleId: null,
        sp: null,
        expressionLevel: null,
        integrationLevel: null,
        antibodies: null,
        intensity: null,
        subjectProteinOrigin: null,
        sourceAccession_TODEBUG: null,
        negativeEvidence: false,
        propertiesNames: [],
        goQualifier: null,
        resourceAXref: false
      },
      {
        resourceId: 648403,
        resourceType: "publication",
        resourceAccession: null,
        resourceDb: null,
        experimentalContextId: 0,
        mdataId: null,
        annotationId: 51978577,
        qualifierType: null,
        qualityQualifier: "GOLD",
        evidenceId: 119516123,
        assignedBy: "Uniprot",
        goAssignedBy: null,
        assignmentMethod: "curated",
        evidenceCodeAC: "ECO:0000269",
        evidenceCodeName: "experimental evidence used in manual assertion",
        evidenceCodeOntology: "EvidenceCodeOntologyCv",
        note: null,
        resourceAssociationType: "evidence",
        valid: true,
        properties: {},
        resourceDescription: null,
        resourceAPublication: true,
        negativeIsoformSpecificity: null,
        cl: null,
        isoformSpecificity: null,
        referenceIdentifierAccession: null,
        sampleId: null,
        sp: null,
        expressionLevel: null,
        integrationLevel: null,
        antibodies: null,
        intensity: null,
        subjectProteinOrigin: null,
        sourceAccession_TODEBUG: null,
        negativeEvidence: false,
        propertiesNames: [],
        goQualifier: null,
        resourceAXref: false
      },
      {
        resourceId: 29257139,
        resourceType: "publication",
        resourceAccession: null,
        resourceDb: null,
        experimentalContextId: 0,
        mdataId: null,
        annotationId: 51978577,
        qualifierType: null,
        qualityQualifier: "GOLD",
        evidenceId: 119516116,
        assignedBy: "Uniprot",
        goAssignedBy: null,
        assignmentMethod: "curated",
        evidenceCodeAC: "ECO:0000269",
        evidenceCodeName: "experimental evidence used in manual assertion",
        evidenceCodeOntology: "EvidenceCodeOntologyCv",
        note: null,
        resourceAssociationType: "evidence",
        valid: true,
        properties: {},
        resourceDescription: null,
        resourceAPublication: true,
        negativeIsoformSpecificity: null,
        cl: null,
        isoformSpecificity: null,
        referenceIdentifierAccession: null,
        sampleId: null,
        sp: null,
        expressionLevel: null,
        integrationLevel: null,
        antibodies: null,
        intensity: null,
        subjectProteinOrigin: null,
        sourceAccession_TODEBUG: null,
        negativeEvidence: false,
        propertiesNames: [],
        goQualifier: null,
        resourceAXref: false
      },
      {
        resourceId: 42609968,
        resourceType: "publication",
        resourceAccession: null,
        resourceDb: null,
        experimentalContextId: 0,
        mdataId: null,
        annotationId: 51978577,
        qualifierType: null,
        qualityQualifier: "GOLD",
        evidenceId: 119516118,
        assignedBy: "Uniprot",
        goAssignedBy: null,
        assignmentMethod: "curated",
        evidenceCodeAC: "ECO:0000269",
        evidenceCodeName: "experimental evidence used in manual assertion",
        evidenceCodeOntology: "EvidenceCodeOntologyCv",
        note: null,
        resourceAssociationType: "evidence",
        valid: true,
        properties: {},
        resourceDescription: null,
        resourceAPublication: true,
        negativeIsoformSpecificity: null,
        cl: null,
        isoformSpecificity: null,
        referenceIdentifierAccession: null,
        sampleId: null,
        sp: null,
        expressionLevel: null,
        integrationLevel: null,
        antibodies: null,
        intensity: null,
        subjectProteinOrigin: null,
        sourceAccession_TODEBUG: null,
        negativeEvidence: false,
        propertiesNames: [],
        goQualifier: null,
        resourceAXref: false
      }
    ],
    indirectEvidenceRefList: null,
    targetingIsoformsMap: {
      "NX_P37840-1": {
        annotationId: 51978577,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-1",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-1",
        positional: false
      },
      "NX_P37840-2": {
        annotationId: 51978577,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-2",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-2",
        positional: false
      },
      "NX_P37840-3": {
        annotationId: 51978577,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-3",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-3",
        positional: false
      }
    },
    properties: [
      {
        annotationId: 51978577,
        valueType: "resource-internal-ref",
        name: "alternative disease description",
        value: "1352453",
        accession: "168601"
      },
      {
        annotationId: 51978577,
        valueType: null,
        name: "rank",
        value: "2",
        accession: null
      }
    ],
    bioObject: null,
    parentXref: null,
    proteoformAnnotation: false,
    wildTypeAnnotation: true,
    apicategory: "DISEASE",
    apiTypeName: "Disease",
    propertiesMap: {
      "alternative disease description": [
        {
          annotationId: 51978577,
          valueType: "resource-internal-ref",
          name: "alternative disease description",
          value: "1352453",
          accession: "168601"
        }
      ],
      rank: [
        {
          annotationId: 51978577,
          valueType: null,
          name: "rank",
          value: "2",
          accession: null
        }
      ]
    },
    categoryName: "Disease",
    rdfPredicate: "disease",
    parentPredicates: ["generalAnnotation", "medical"]
  },
  {
    subjectComponents: null,
    annotationName: null,
    annotationHash: null,
    isoformsDisplayedAsSpecific: [],
    synonyms: null,
    uniqueName: "AN_P37840_000808",
    cvTermAccessionCode: "DI-02135",
    cvTermName: "Parkinson disease 4, autosomal dominant",
    cvTermType: null,
    cvTermDescription:
      "A complex neurodegenerative disorder with manifestations ranging from typical Parkinson disease to dementia with Lewy bodies. Clinical features include parkinsonian symptoms (resting tremor, rigidity, postural instability and bradykinesia), dementia, diffuse Lewy body pathology, autonomic dysfunction, hallucinations and paranoia.",
    cvApiName: "UniprotDiseaseCv",
    description:
      "Parkinson disease 4, autosomal dominant (PARK4) [MIM:605543]: A complex neurodegenerative disorder with manifestations ranging from typical Parkinson disease to dementia with Lewy bodies. Clinical features include parkinsonian symptoms (resting tremor, rigidity, postural instability and bradykinesia), dementia, diffuse Lewy body pathology, autonomic dysfunction, hallucinations and paranoia. The disease is caused by mutations affecting the gene represented in this entry.",
    category: "disease",
    qualityQualifier: "GOLD",
    annotationId: 51978578,
    variant: null,
    synonym: null,
    evidences: [
      {
        resourceId: 1352405,
        resourceType: "database",
        resourceAccession: "P37840",
        resourceDb: "UniProt",
        experimentalContextId: 0,
        mdataId: null,
        annotationId: 51978578,
        qualifierType: null,
        qualityQualifier: "GOLD",
        evidenceId: 119516126,
        assignedBy: "Uniprot",
        goAssignedBy: null,
        assignmentMethod: "curated",
        evidenceCodeAC: "ECO:0000269",
        evidenceCodeName: "experimental evidence used in manual assertion",
        evidenceCodeOntology: "EvidenceCodeOntologyCv",
        note: null,
        resourceAssociationType: "evidence",
        valid: true,
        properties: {},
        resourceDescription: "UniProt web site",
        resourceAPublication: false,
        negativeIsoformSpecificity: null,
        cl: null,
        isoformSpecificity: null,
        referenceIdentifierAccession: null,
        sampleId: null,
        sp: null,
        expressionLevel: null,
        integrationLevel: null,
        antibodies: null,
        intensity: null,
        subjectProteinOrigin: null,
        sourceAccession_TODEBUG: null,
        negativeEvidence: false,
        propertiesNames: [],
        goQualifier: null,
        resourceAXref: true
      }
    ],
    indirectEvidenceRefList: null,
    targetingIsoformsMap: {
      "NX_P37840-1": {
        annotationId: 51978578,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-1",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-1",
        positional: false
      },
      "NX_P37840-2": {
        annotationId: 51978578,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-2",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-2",
        positional: false
      },
      "NX_P37840-3": {
        annotationId: 51978578,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-3",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-3",
        positional: false
      }
    },
    properties: [
      {
        annotationId: 51978578,
        valueType: "resource-internal-ref",
        name: "alternative disease description",
        value: "1352454",
        accession: "605543"
      },
      {
        annotationId: 51978578,
        valueType: null,
        name: "rank",
        value: "3",
        accession: null
      }
    ],
    bioObject: null,
    parentXref: null,
    proteoformAnnotation: false,
    wildTypeAnnotation: true,
    apicategory: "DISEASE",
    apiTypeName: "Disease",
    propertiesMap: {
      "alternative disease description": [
        {
          annotationId: 51978578,
          valueType: "resource-internal-ref",
          name: "alternative disease description",
          value: "1352454",
          accession: "605543"
        }
      ],
      rank: [
        {
          annotationId: 51978578,
          valueType: null,
          name: "rank",
          value: "3",
          accession: null
        }
      ]
    },
    categoryName: "Disease",
    rdfPredicate: "disease",
    parentPredicates: ["generalAnnotation", "medical"]
  },
  {
    subjectComponents: null,
    annotationName: null,
    annotationHash: null,
    isoformsDisplayedAsSpecific: [],
    synonyms: null,
    uniqueName: "AN_P37840_XR_1142377",
    cvTermAccessionCode: null,
    cvTermName: null,
    cvTermType: null,
    cvTermDescription: null,
    cvApiName: null,
    description: "Young adult-onset Parkinsonism",
    category: "disease",
    qualityQualifier: "GOLD",
    annotationId: 100001142377,
    variant: null,
    synonym: null,
    evidences: [
      {
        resourceId: 1142377,
        resourceType: "database",
        resourceAccession: "2828",
        resourceDb: "Orphanet",
        experimentalContextId: null,
        mdataId: null,
        annotationId: 100001142377,
        qualifierType: "IC",
        qualityQualifier: "GOLD",
        evidenceId: 300001142377,
        assignedBy: "Orphanet",
        goAssignedBy: null,
        assignmentMethod: "curated",
        evidenceCodeAC: "ECO:0000305",
        evidenceCodeName: "curator inference used in manual assertion",
        evidenceCodeOntology: "EvidenceCodeOntologyCv",
        note: null,
        resourceAssociationType: "evidence",
        valid: true,
        properties: {},
        resourceDescription: null,
        resourceAPublication: false,
        negativeIsoformSpecificity: null,
        cl: null,
        isoformSpecificity: null,
        referenceIdentifierAccession: null,
        sampleId: null,
        sp: null,
        expressionLevel: null,
        integrationLevel: null,
        antibodies: null,
        intensity: null,
        subjectProteinOrigin: null,
        sourceAccession_TODEBUG: null,
        negativeEvidence: false,
        propertiesNames: [],
        goQualifier: null,
        resourceAXref: true
      }
    ],
    indirectEvidenceRefList: null,
    targetingIsoformsMap: {
      "NX_P37840-1": {
        annotationId: 100001142377,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-1",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-1",
        positional: false
      },
      "NX_P37840-2": {
        annotationId: 100001142377,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-2",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-2",
        positional: false
      },
      "NX_P37840-3": {
        annotationId: 100001142377,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-3",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-3",
        positional: false
      }
    },
    properties: [],
    bioObject: null,
    parentXref: {
      dbXrefId: 1142377,
      accession: "2828",
      databaseName: "Orphanet",
      databaseCategory: "Organism-specific databases",
      url: "http://www.orpha.net/consor/cgi-bin/index.php",
      resolvedUrl:
        "http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=GB&Expert=2828",
      linkUrl:
        "http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=GB&Expert=%s",
      properties: [
        {
          dbXrefId: 1142377,
          propertyId: 12265004,
          name: "disease",
          value: "Young adult-onset Parkinsonism"
        }
      ]
    },
    proteoformAnnotation: false,
    wildTypeAnnotation: true,
    apicategory: "DISEASE",
    apiTypeName: "Disease",
    propertiesMap: {},
    categoryName: "Disease",
    rdfPredicate: "disease",
    parentPredicates: ["generalAnnotation", "medical"]
  },
  {
    subjectComponents: null,
    annotationName: null,
    annotationHash: null,
    isoformsDisplayedAsSpecific: [],
    synonyms: null,
    uniqueName: "AN_P37840_XR_1297516",
    cvTermAccessionCode: null,
    cvTermName: null,
    cvTermType: null,
    cvTermDescription: null,
    cvApiName: null,
    description: "Parkinsonian-pyramidal syndrome",
    category: "disease",
    qualityQualifier: "GOLD",
    annotationId: 100001297516,
    variant: null,
    synonym: null,
    evidences: [
      {
        resourceId: 1297516,
        resourceType: "database",
        resourceAccession: "171695",
        resourceDb: "Orphanet",
        experimentalContextId: null,
        mdataId: null,
        annotationId: 100001297516,
        qualifierType: "IC",
        qualityQualifier: "GOLD",
        evidenceId: 300001297516,
        assignedBy: "Orphanet",
        goAssignedBy: null,
        assignmentMethod: "curated",
        evidenceCodeAC: "ECO:0000305",
        evidenceCodeName: "curator inference used in manual assertion",
        evidenceCodeOntology: "EvidenceCodeOntologyCv",
        note: null,
        resourceAssociationType: "evidence",
        valid: true,
        properties: {},
        resourceDescription: null,
        resourceAPublication: false,
        negativeIsoformSpecificity: null,
        cl: null,
        isoformSpecificity: null,
        referenceIdentifierAccession: null,
        sampleId: null,
        sp: null,
        expressionLevel: null,
        integrationLevel: null,
        antibodies: null,
        intensity: null,
        subjectProteinOrigin: null,
        sourceAccession_TODEBUG: null,
        negativeEvidence: false,
        propertiesNames: [],
        goQualifier: null,
        resourceAXref: true
      }
    ],
    indirectEvidenceRefList: null,
    targetingIsoformsMap: {
      "NX_P37840-1": {
        annotationId: 100001297516,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-1",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-1",
        positional: false
      },
      "NX_P37840-2": {
        annotationId: 100001297516,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-2",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-2",
        positional: false
      },
      "NX_P37840-3": {
        annotationId: 100001297516,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-3",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-3",
        positional: false
      }
    },
    properties: [],
    bioObject: null,
    parentXref: {
      dbXrefId: 1297516,
      accession: "171695",
      databaseName: "Orphanet",
      databaseCategory: "Organism-specific databases",
      url: "http://www.orpha.net/consor/cgi-bin/index.php",
      resolvedUrl:
        "http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=GB&Expert=171695",
      linkUrl:
        "http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=GB&Expert=%s",
      properties: [
        {
          dbXrefId: 1297516,
          propertyId: 261082,
          name: "disease",
          value: "Parkinsonian-pyramidal syndrome"
        },
        {
          dbXrefId: 1297516,
          propertyId: 1004693296,
          name: "assigned by",
          value: "GeneRif"
        }
      ]
    },
    proteoformAnnotation: false,
    wildTypeAnnotation: true,
    apicategory: "DISEASE",
    apiTypeName: "Disease",
    propertiesMap: {},
    categoryName: "Disease",
    rdfPredicate: "disease",
    parentPredicates: ["generalAnnotation", "medical"]
  },
  {
    subjectComponents: null,
    annotationName: null,
    annotationHash: null,
    isoformsDisplayedAsSpecific: [],
    synonyms: null,
    uniqueName: "AN_P37840_XR_1437956",
    cvTermAccessionCode: null,
    cvTermName: null,
    cvTermType: null,
    cvTermDescription: null,
    cvApiName: null,
    description: "Dementia with Lewy body",
    category: "disease",
    qualityQualifier: "GOLD",
    annotationId: 100001437956,
    variant: null,
    synonym: null,
    evidences: [
      {
        resourceId: 1437956,
        resourceType: "database",
        resourceAccession: "1648",
        resourceDb: "Orphanet",
        experimentalContextId: null,
        mdataId: null,
        annotationId: 100001437956,
        qualifierType: "IC",
        qualityQualifier: "GOLD",
        evidenceId: 300001437956,
        assignedBy: "Orphanet",
        goAssignedBy: null,
        assignmentMethod: "curated",
        evidenceCodeAC: "ECO:0000305",
        evidenceCodeName: "curator inference used in manual assertion",
        evidenceCodeOntology: "EvidenceCodeOntologyCv",
        note: null,
        resourceAssociationType: "evidence",
        valid: true,
        properties: {},
        resourceDescription: null,
        resourceAPublication: false,
        negativeIsoformSpecificity: null,
        cl: null,
        isoformSpecificity: null,
        referenceIdentifierAccession: null,
        sampleId: null,
        sp: null,
        expressionLevel: null,
        integrationLevel: null,
        antibodies: null,
        intensity: null,
        subjectProteinOrigin: null,
        sourceAccession_TODEBUG: null,
        negativeEvidence: false,
        propertiesNames: [],
        goQualifier: null,
        resourceAXref: true
      }
    ],
    indirectEvidenceRefList: null,
    targetingIsoformsMap: {
      "NX_P37840-1": {
        annotationId: 100001437956,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-1",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-1",
        positional: false
      },
      "NX_P37840-2": {
        annotationId: 100001437956,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-2",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-2",
        positional: false
      },
      "NX_P37840-3": {
        annotationId: 100001437956,
        firstPosition: null,
        lastPosition: null,
        isoformAccession: "NX_P37840-3",
        specificity: "UNKNOWN",
        name: null,
        isoformName: "NX_P37840-3",
        positional: false
      }
    },
    properties: [],
    bioObject: null,
    parentXref: {
      dbXrefId: 1437956,
      accession: "1648",
      databaseName: "Orphanet",
      databaseCategory: "Organism-specific databases",
      url: "http://www.orpha.net/consor/cgi-bin/index.php",
      resolvedUrl:
        "http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=GB&Expert=1648",
      linkUrl:
        "http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=GB&Expert=%s",
      properties: [
        {
          dbXrefId: 1437956,
          propertyId: 25008887,
          name: "disease",
          value: "Dementia with Lewy body"
        }
      ]
    },
    proteoformAnnotation: false,
    wildTypeAnnotation: true,
    apicategory: "DISEASE",
    apiTypeName: "Disease",
    propertiesMap: {},
    categoryName: "Disease",
    rdfPredicate: "disease",
    parentPredicates: ["generalAnnotation", "medical"]
  }
];

export const OverviewData = [
  {
    entry: {
      properties: {
        interactionCount: 267,
        maxSeqLen: 140,
        filterstructure: true,
        filterdisease: true,
        filterexpressionprofile: true
      },
      uniqueName: "NX_P37840",
      overview: {
        history: {
          proteinExistenceUniprot: {
            name: "protein level",
            description: "Evidence at protein level",
            descriptionName: "Evidence_at_protein_level",
            level: 1
          },
          nextprotIntegrationDate: 1267471422488,
          nextprotUpdateDate: 1535998616146,
          uniprotIntegrationDate: 781005600000,
          uniprotUpdateDate: 1536746400000,
          uniprotVersion: "216",
          lastSequenceUpdate: 780966000000,
          sequenceVersion: "1",
          formattedNextprotIntegrationDate: "2010-03-01",
          formattedNextprotUpdateDate: "2018-09-03",
          formattedUniprotIntegrationDate: "1994-10-01",
          formattedUniprotUpdateDate: "2018-09-12"
        },
        families: [
          {
            familyId: 68266,
            accession: "FA-03906",
            name: "Synuclein",
            level: "Family",
            description: "Belongs to the synuclein family.",
            region: null,
            parent: null
          }
        ],
        proteinNames: [
          {
            clazz: "PROTEIN_NAMES",
            type: "name",
            qualifier: "full",
            id: "PR_745056",
            category: "protein",
            name: "Alpha-synuclein",
            parentId: null,
            mainEntityName: null,
            synonyms: [
              {
                clazz: "PROTEIN_NAMES",
                type: "name",
                qualifier: "full",
                id: "PR_745049",
                category: "protein",
                name: "Non-A beta component of AD amyloid",
                parentId: "PR_745056",
                mainEntityName: null,
                synonyms: [],
                value: "Non-A beta component of AD amyloid",
                otherRecommendedEntityNames: [],
                main: false,
                composedName: "full name"
              },
              {
                clazz: "PROTEIN_NAMES",
                type: "name",
                qualifier: "full",
                id: "PR_745048",
                category: "protein",
                name: "Non-A4 component of amyloid precursor",
                parentId: "PR_745056",
                mainEntityName: null,
                synonyms: [
                  {
                    clazz: "PROTEIN_NAMES",
                    type: "name",
                    qualifier: "short",
                    id: "PR_745051",
                    category: "protein",
                    name: "NACP",
                    parentId: "PR_745048",
                    mainEntityName: null,
                    synonyms: [],
                    value: "NACP",
                    otherRecommendedEntityNames: [],
                    main: false,
                    composedName: "short name"
                  }
                ],
                value: "Non-A4 component of amyloid precursor",
                otherRecommendedEntityNames: [],
                main: false,
                composedName: "full name"
              }
            ],
            value: "Alpha-synuclein",
            otherRecommendedEntityNames: [],
            main: true,
            composedName: "full name"
          }
        ],
        geneNames: [
          {
            clazz: "GENE_NAMES",
            type: "gene name",
            qualifier: null,
            id: "PR_1202899",
            category: "gene name",
            name: "SNCA",
            parentId: null,
            mainEntityName: null,
            synonyms: [
              {
                clazz: "GENE_NAMES",
                type: "gene name",
                qualifier: null,
                id: "PR_1202900",
                category: "gene name",
                name: "NACP",
                parentId: "PR_1202899",
                mainEntityName: null,
                synonyms: [],
                value: "NACP",
                otherRecommendedEntityNames: [],
                main: false,
                composedName: "gene name"
              },
              {
                clazz: "GENE_NAMES",
                type: "gene name",
                qualifier: null,
                id: "PR_1202901",
                category: "gene name",
                name: "PARK1",
                parentId: "PR_1202899",
                mainEntityName: null,
                synonyms: [],
                value: "PARK1",
                otherRecommendedEntityNames: [],
                main: false,
                composedName: "gene name"
              }
            ],
            value: "SNCA",
            otherRecommendedEntityNames: [],
            main: true,
            composedName: "gene name"
          }
        ],
        functionalRegionNames: [],
        cleavedRegionNames: [],
        additionalNames: [],
        isoformNames: [
          {
            clazz: null,
            type: "name",
            qualifier: null,
            id: null,
            category: null,
            name: "Iso 1",
            parentId: null,
            mainEntityName: null,
            synonyms: [
              {
                clazz: null,
                type: null,
                qualifier: null,
                id: null,
                category: null,
                name: "NACP140",
                parentId: null,
                mainEntityName: null,
                synonyms: [],
                value: "NACP140",
                otherRecommendedEntityNames: [],
                main: false,
                composedName: null
              }
            ],
            value: "Iso 1",
            otherRecommendedEntityNames: [],
            main: true,
            composedName: "name"
          },
          {
            clazz: null,
            type: "name",
            qualifier: null,
            id: null,
            category: null,
            name: "2-4",
            parentId: null,
            mainEntityName: null,
            synonyms: [
              {
                clazz: null,
                type: null,
                qualifier: null,
                id: null,
                category: null,
                name: "NACP112",
                parentId: null,
                mainEntityName: null,
                synonyms: [],
                value: "NACP112",
                otherRecommendedEntityNames: [],
                main: false,
                composedName: null
              }
            ],
            value: "2-4",
            otherRecommendedEntityNames: [],
            main: true,
            composedName: "name"
          },
          {
            clazz: null,
            type: "name",
            qualifier: null,
            id: null,
            category: null,
            name: "2-5",
            parentId: null,
            mainEntityName: null,
            synonyms: [],
            value: "2-5",
            otherRecommendedEntityNames: [],
            main: true,
            composedName: "name"
          }
        ],
        proteinExistences: {
          entryAccession: "NX_P37840",
          proteinExistenceInferred: {
            proteinExistence: {
              name: "protein level",
              description: "Evidence at protein level",
              descriptionName: "Evidence_at_protein_level",
              level: 1
            },
            rule: "SP_PER_01"
          },
          otherProteinExistenceUniprot: {
            name: "protein level",
            description: "Evidence at protein level",
            descriptionName: "Evidence_at_protein_level",
            level: 1
          },
          otherProteinExistenceNexprot1: {
            name: "protein level",
            description: "Evidence at protein level",
            descriptionName: "Evidence_at_protein_level",
            level: 1
          }
        },
        recommendedProteinName: {
          clazz: "PROTEIN_NAMES",
          type: "name",
          qualifier: "full",
          id: "PR_745056",
          category: "protein",
          name: "Alpha-synuclein",
          parentId: null,
          mainEntityName: null,
          synonyms: [],
          value: "Alpha-synuclein",
          otherRecommendedEntityNames: [],
          main: true,
          composedName: "full name"
        },
        mainProteinName: "Alpha-synuclein",
        mainGeneName: "SNCA",
        alternativeProteinNames: [
          {
            clazz: "PROTEIN_NAMES",
            type: "name",
            qualifier: "full",
            id: "PR_745049",
            category: "protein",
            name: "Non-A beta component of AD amyloid",
            parentId: "PR_745056",
            mainEntityName: null,
            synonyms: [],
            value: "Non-A beta component of AD amyloid",
            otherRecommendedEntityNames: [],
            main: false,
            composedName: "full name"
          },
          {
            clazz: "PROTEIN_NAMES",
            type: "name",
            qualifier: "full",
            id: "PR_745048",
            category: "protein",
            name: "Non-A4 component of amyloid precursor",
            parentId: "PR_745056",
            mainEntityName: null,
            synonyms: [
              {
                clazz: "PROTEIN_NAMES",
                type: "name",
                qualifier: "short",
                id: "PR_745051",
                category: "protein",
                name: "NACP",
                parentId: "PR_745048",
                mainEntityName: null,
                synonyms: [],
                value: "NACP",
                otherRecommendedEntityNames: [],
                main: false,
                composedName: "short name"
              }
            ],
            value: "Non-A4 component of amyloid precursor",
            otherRecommendedEntityNames: [],
            main: false,
            composedName: "full name"
          }
        ]
      },
      uniprotName: "P37840"
    },
    StringUtils: "org.nextprot.api.commons.utils.StringUtils",
    NXUtils: "org.nextprot.api.core.utils.NXVelocityUtils"
  }
];
